# Define stages
stages:
  - build
  - lint
  - test
  - security

# Cache dependencies
cache:
  paths:
    - client/node_modules/
    - server/node_modules/

# Build stage for client (Vite)
build_client:
  stage: build
  image: node:20
  script:
    - echo "Installing dependencies for Vite client..."
    - cd client
    - npm install
    - echo "Building the Vite client project..."
    - npm run build
  artifacts:
    paths:
      - client/dist/

# Build stage for server
build_server:
  stage: build
  image: node:20
  script:
    - echo "Installing dependencies for server..."
    - cd server
    - npm install
    - echo "Building the server project..."
    - npm run build
  artifacts:
    paths:
      - server/dist/