image: node:20

stages:
  - build

cache:
  paths:
    - node_modules/

before_script:
  - npm install

build:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist/
