image: node:20

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g firebase-tools netlify-cli

build:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist/

deploy:
  stage: deploy
  script:
    - cd frontend
    - firebase deploy --token $FIREBASE_TOKEN
    - netlify deploy --prod --dir=dist --auth=$NETLIFY_AUTH_TOKEN
  only:
    - main
  dependencies:
    - build
