# Define stages
stages:
  - build
  - lint
  - test
  - security

# Cache dependencies
cache:
  paths:
    - node_modules/

# Build stage
build:
  stage: build
  image: node:16
  script:
    - echo "Installing dependencies..."
    - npm install
    - echo "Building the project..."
    - npm run build
  artifacts:
    paths:
      - dist/

# Lint stage
lint:
  stage: lint
  image: node:16
  script:
    - echo "Linting the code..."
    - npm install
    - npm run lint

# Test stage
test:
  stage: test
  image: node:16
  script:
    - echo "Running tests..."
    - npm install
    - npm test

# Security scanning stage
security:
  stage: security
  image: node:16
  script:
    - echo "Running security scan..."
    - npm install
    - npm audit

# Notifications
after_script:
  - |
    if [ "$CI_JOB_STATUS" == "failed" ]; then
      curl -X POST -H 'Content-type: application/json' --data '{"text":"Build failed: $CI_PROJECT_NAME - $CI_JOB_NAME"}' $SLACK_WEBHOOK_URL
    fi
  - |
    if [ "$CI_JOB_STATUS" == "success" ]; then
      curl -X POST -H 'Content-type: application/json' --data '{"text":"Build succeeded: $CI_PROJECT_NAME - $CI_JOB_NAME"}' $SLACK_WEBHOOK_URL
    fi