image: node:20

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g firebase-tools

build:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/build/

deploy:
  stage: deploy
  script:
    - firebase deploy --token $FIREBASE_TOKEN
  only:
    - main
