version: '3'  # Specify the version of Docker Compose

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - schoolbridge-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongodb:
    image: mongo
    networks:
      - schoolbridge-network

networks:
  schoolbridge-network:
    driver: bridge
