version: '3'  # Specify the version of Docker Compose

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - schoolbridge-network
  
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongodb:
    image: mongo
    networks:
      - schoolbridge-network

networks:
  schoolbridge-network:  # Define the network here
    driver: bridge  # Optional: specify the driver (default is bridge)